src/App.scss
src/components/messages/ChatInvites/index.tsx
src/components/messages/NewChat/index.tsx
src/components/messages/ThreadSelector/index.tsx

- The number of invites was inaccurate because we keep record of invites, and the badge wasn't filtered
- After the code freeze, when we can work more comfortably, there will be a tiny refactor to remove the need for filtering in every instance, just not comfortable doing that now.

Fix invite count

---

src/App.scss

- Helps with the mobile chat window issue shown in screenshot for now, but not a final solution to this.

fix(css): set height for `.Main` to ensure height fill on mobile

---

src/components/messages/ThreadSelector/ThreadSelector.scss
src/components/messages/ThreadWindow/ThreadWindow.scss

- Removed height 100% on threads classname to avoid pushing the next element down to the bottom
- Replaced `flex-flow: column wrap` with `flex-direction: column` to avoid issues on smaller devices (eg: iPhone SE)

fix(threads-height): removed height 100% to avoid pushing the empty box to the bottom

---

src/components/account/Avatar/index.tsx
src/components/messages/NewChat/NewChat.scss
src/components/messages/NewChat/SearchSuggestions/SearchSuggestions.scss
src/components/messages/NewChat/SearchSuggestions/index.tsx
src/components/messages/NewChat/index.tsx

- Add SearchSuggestion component
- Use it in new chat
- Make it work in mobile and desktop
- Using `thegraph` for its ens domain subgraph
Although it does use graphql, I did not feel it appropriate to add a graphql package or spend time on a util when this is our only graphql use case, therefore I went with a hardcoded query string.

Add SearchSuggestion component

---

package.json
src/components/messages/MessageBox/index.tsx
src/components/messages/ThreadWindow/index.tsx
src/w3iProxy/chatProviders/internalChatProvider.ts
src/w3iProxy/w3iChatFacade.ts
yarn.lock

- Implements a simplistic message queue
~~This PR works, theoretically, and will work practically (:crossed_fingers: ) once [this PR](https://github.com/WalletConnect/chat-client-js/pull/35) gets merged in~~
This PR works now that [this PR](https://github.com/WalletConnect/chat-client-js/pull/35) has been merged in. 
This feature does not work on Firefox, but does work on chrome. This feature working on Firefox is blocked by an issue in core and has to do with re-connection, outside the scope of this PR.
Showing and styling unsent messages will be done in another PR, this is purely functionality.
- When `message` is called at the top level, it simply "queues" the message by populating a `ReplaySubject` ([Read More](https://rxjs.dev/api/index/class/ReplaySubject))
- One subscriber is …

Implement new message queue

---

src/components/account/Avatar/index.tsx
src/components/general/Spinner/index.tsx
src/components/messages/ThreadSelector/Thread/index.tsx
src/components/messages/ThreadWindow/index.tsx
src/components/utils/AuthProtectedPage.tsx
src/contexts/W3iContext/context.ts
src/contexts/W3iContext/index.tsx
src/pages/Login/index.tsx

- Login page becomes a spinner when `chatProvider !== "internal"`
- Login page now redirects to intended page when authenticated. Eg going to `/notifications` when authenticated will actually go to `/notifications` instead of `/messages`

Add authenticated redirection

---

src/w3iProxy/pushProviders/externalPushProvider.ts
src/w3iProxy/pushProviders/internalPushProvider.ts
src/w3iProxy/pushProviders/types.ts
src/w3iProxy/w3iPushFacade.ts

- As discussed with @Cali93 @devceline @llbartekll 
- Expose `PushWalletClient.subscribe` method for externalProvider demo purposes
- InternalProvider usage is a no-op until JS Push has `wc_pushSubscribe` implemented.

feat: expose `pushWalletClient.subscribe` for external providers

---

src/w3iProxy/chatProviders/externalChatProvider.ts
src/w3iProxy/externalCommunicators/reactNativeCommunicator.ts
src/w3iProxy/pushProviders/externalPushProvider.ts
src/w3iProxy/w3iChatFacade.ts
src/w3iProxy/w3iPushFacade.ts

- Add `ReactNativeCommunicator` to communicate with react native webviews
- It is accessed through `chatProvider=reactnative` and of course `pushProvider=reactnative`
- Adapted `ExternalProvider` to use the new communicator when requested

Add React Native communicator

---

src/contexts/W3iContext/context.ts
src/contexts/W3iContext/index.tsx
src/pages/Login/SignatureModal/SignatureModal.scss
src/pages/Login/SignatureModal/index.tsx

Allow to cancel out of signature modal. 
Also, it remembers your progress so if one person signed an identity key, canceled out of modal and then tried to connect their account again, they'd only have to register their sync key.
| Before       | After        |
| ------------ | ------------ |
| ![image](https://user-images.githubusercontent.com/61278030/234324483-5cddac14-45b1-413b-94e7-a87ae745da59.png) | ![image](https://user-images.githubusercontent.com/61278030/234324208-710f2573-e4f1-4e86-8da9-dd9799df9721.png) |

Update signature modal to allow for cancel

---

.eslintrc.json
src/App.tsx
src/components/layout/Sidebar/index.tsx
src/contexts/W3iContext/context.ts
src/contexts/W3iContext/index.tsx
src/main.tsx
src/pages/Login/index.tsx
src/routes.tsx
src/w3iProxy/index.ts

Allow to configure UIs by setting relevant flags in params: `chatEnabled`, `pushEnabled` and `settingsEnabled`.  They are enabled by default.
If only one is enabled, the sidebar is hidden.
Fixes #101 
**Note**: Even if `chatEnabled=false`, a `chatProvider=external` must still be provided as the chat proxy is what handles accounts, for now.

Allow for managing what UIs are available

---

src/components/general/Checkbox/index.tsx
src/contexts/W3iContext/index.tsx
src/pages/Login/index.tsx
src/pages/ScanQrCode/index.tsx
src/utils/address.ts
src/utils/hooks.ts
src/w3iProxy/authProviders/externalAuthProvider.ts
src/w3iProxy/authProviders/internalAuthProvider.ts
src/w3iProxy/authProviders/types.ts
src/w3iProxy/chatProviders/externalChatProvider.ts
src/w3iProxy/chatProviders/internalChatProvider.ts
src/w3iProxy/index.ts
src/w3iProxy/w3iAuthFacade.ts
src/w3iProxy/w3iChatFacade.ts

- Add dedicated auth facade
- Refactor userPubKey in app to use auth facade
- Remove old/useless console.log
For w3iSdk, implementing this using the `account` query param will not change anything, but for dynamic account changing, the `setAccount` rpc request needs to go through `window.web3inbox.auth` not `window.web3inbox.chat`. 
The only change needed `account` query param is adding `authProvider=external` in the query params

Refactor to use auth provider

---

src/components/notifications/AppNotifications/AppNotificationDropdown/index.tsx
src/components/notifications/AppNotifications/index.tsx
src/components/notifications/NotificationsLayout/UnsubscribeModal/index.tsx

- Hookup unsub modal
- Redirect `/notifications` instead of display 404 when going to a non-existing app

Hookup unsubscribe modal

---

src/components/notifications/AppNotifications/index.tsx

- Use `publishedAt` instead of `Date.now()`
- Change `read` to default to `false` since we do manage read status at the moment.

Fix timestamp not being correct

---

src/contexts/W3iContext/index.tsx
src/w3iProxy/chatProviders/externalChatProvider.ts
src/w3iProxy/chatProviders/internalChatProvider.ts
src/w3iProxy/listenerTypes.ts
src/w3iProxy/pushProviders/externalPushProvider.ts

- Create separate event for `sync_update`s coming from notify and chat
- Listen to them in external providers
- Based on this spec change: https://github.com/WalletConnect/walletconnect-docs/pull/674

Refactor to use sync updates

---

src/components/notifications/AppExplorer/AppCard/index.tsx
src/components/notifications/NotificationsLayout/PreferencesModal/index.tsx
src/components/notifications/NotificationsLayout/UnsubscribeModal/index.tsx
src/w3iProxy/authProviders/types.ts
src/w3iProxy/chatProviders/types.ts
src/w3iProxy/observablesController.ts
src/w3iProxy/pushProviders/types.ts
src/w3iProxy/w3iAuthFacade.ts
src/w3iProxy/w3iChatFacade.ts
src/w3iProxy/w3iPushFacade.ts

- Add `ObservablesController` which removes a lot of the copy paste in observing between the facades
- `once` -> `observeOne`
- Removing direct access from the emitter promotes using the observables, which has two main benefits:
- enforces consistent dev experience across the entire app
- maintains the ability to `pipe` stuff to observers in the future in case we need to
- We don't need `off` or `removeListener` since when subscribing to a observer, you have access to the `subscription` object and take complete ownership of it

Refactor to use central observablesController

---

src/w3iProxy/observablesController.ts

The observe and observeOne functions were to bound to `this` and so were calling the parent facade as `this` which does not contain `getObservable` method. This fixes that.

Bind observe functions

---

src/components/general/BackButton/BackButton.scss
src/components/general/BackButton/index.tsx
src/components/messages/ThreadWindow/ThreadWindow.scss

Adjusted some padding & margins for a correct UI & bigger tap area for back button
Resolves https://github.com/WalletConnect/web3inbox/issues/152

adding padding around back button

---

src/components/notifications/AppNotifications/AppNotifications.scss
src/components/notifications/AppNotifications/AppNotificationsEmpty/AppNotificationsEmpty.scss
src/components/notifications/AppNotifications/AppNotificationsEmpty/index.tsx
src/components/notifications/AppNotifications/index.tsx

I've added an empty state when there are no notifications
Resolves https://github.com/WalletConnect/web3inbox/issues/157
https://web3inbox-dev-hidden-git-feat-notificatio-6926ba-walletconnect1.vercel.app/login?next=%2Fmessages

[:feat] add empty state when there are no notifications

---

src/contexts/W3iContext/hooks/pushHooks.ts

-  Bubble the subscription event to the parent ,
- In service of https://github.com/WalletConnect/web3inbox-widget/pull/4

Bubble subscription event

---

package.json
src/components/notifications/AppNotifications/AppNotificationItem.tsx
yarn.lock

- Fixes typo in "Visit Link" copy
- Ensures w3i is using latest `@walletconnect/core`. Was still seeing the patched `Failed to decrypt` for empty cast messages.

fix: typo in external link copy + core dep

---

package.json
src/App.tsx
src/main-sw.ts
vite.config.ts
yarn.lock

- Change register to not inject index file, this achieves two things:
- First, we lose offline work. Not a big loss since our app really needs a connection.
- Second, we no longer get an issue where we get an outdated index file that fetches an incorrect bundle name
- This just makes the service worker a way to more efficiently catch pictures and the like

Change policy injection

---

src/pages/widget/Subscribe/index.tsx

- Add loading state to enable (subscribe) in widget views

Fix no loading in enable

---

src/utils/hooks/usePushProjects.ts
src/utils/types.ts

This reverts commit 1b6688d18f2700b22aa2cdf1b96a58d14062e238.
- This was a workaround/override behaviour we used on the notify refactor branch to specifically target `notify.gm.walletconnect.com` in the w3i explorer
- `gm-dapp`'s homepage field has now been updated so this is no longer needed, i.e. we should always point to the `homepage` field going forward as before.

Revert "fix: resolve `.well-known` assets via app.browser field for testing

---

src/components/notifications/AppSelector/index.tsx

- Add `handleImageFallback` to app-selector logo

fix: add imagefall back for app selector logo

---

src/Modals.tsx
src/components/settings/NotificationsSettings/index.tsx
src/components/utils/NotificationPwaModal/index.tsx
src/firebase-messaging-sw.ts
src/utils/notifications.ts
src/w3iProxy/notifyProviders/internalNotifyProvider.ts

**TL;DR: There's a race condition that causes the push notifications to be considered "silent push messages" which are flagged by the browser/OS as suspicious. Causing odd messages before every PN on desktop ("This site has been upgraded in the background") and lack of reliability on iOS. This should fix it.**
According to the sources below, not awaiting the `showNotification` and technically firing it after the listener resolves is a red flag for the browser/OS. 
- [StackOverflow, Chrome PNs causing odd messages "Site has been upgraded in the background"](https://stackoverflow.com/questions/31108699/chrome-push-notification-this-site-has-been-updated-in-the-background)
- [web.dev, handling push notifications](https://web.dev/articles/push-notifications-handling-messages#:~:text=Calling%20 …

chore: return show notification function

---

src/components/notifications/AppSelector/index.tsx
src/components/notifications/NotificationsLayout/index.tsx
src/components/settings/NotificationsSettings/index.tsx
src/utils/constants.ts
src/utils/hooks/useNotifyProjects.ts
src/utils/idb.ts

- Run prettier on unformatted files
- Fix a bug in `NotificationsLayout` where user was being redirected to `/new-app` even when they had existing subscriptions (on mobile), which is not the intended experience
- This fixes it to intended UX:
- On desktop, always go to `/notifications/new-app` when on `/notifications` (as we have the screen space to display the selector an the explorer
- On mobile, only go `/notifications/new-app` if there are no subscriptions

fix: redirect when there are no subs

---

src/components/notifications/AppExplorer/AppCard/index.tsx
src/components/notifications/AppExplorer/index.tsx
src/components/settings/NotificationsSettings/index.tsx
src/utils/hooks/useNotifyProjects.ts

- Only show featured apps when dev mode is disabled
- Do not show featured badge
- Based on [this slack thread](https://walletconnect.slack.com/archives/C044SKFKELR/p1701097389794339)

chore: do not use featuredicon

---

src/components/notifications/AppNotifications/AppNotificationsHeader/AppNotificationsHeader.scss
src/components/notifications/AppNotifications/AppNotificationsHeader/index.tsx
src/components/notifications/AppNotifications/index.tsx

Added domain to header on desktop and handled long domain & dApp name states.
Seems like we'll be adding the domain on the mobile as well but wanted to answer for my question [here](https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg?node-id=2903:62421&mode=dev#629166293).
Fixes: https://github.com/WalletConnect/web3inbox/issues/299#issue-2018125756

feat: add domain to header

---

src/components/notifications/AppNotifications/AppNotificationItem.tsx
src/index.css

Refactored "show more/less" logic since the previous solution isn't quite useful when we change the screen sizes. It doesn't respect the content. Instead of using `line-clamp` and calculating the text size, this is a better solution so it doesn't require us to calculate element heights.
Another solution would be to listen screen size change and update the visibility value but this is not performant way to implement it. Once we have lots of notifications in a page, this might bring perfomance issues in the screen. Let's just keep is as simple as possible.
Please put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …

refactor: update show more logic

---

src/components/general/Button/Button.scss
src/components/general/Modal/Modal.tsx
src/components/notifications/NotificationsLayout/PreferencesModal/index.tsx
src/components/notifications/NotificationsLayout/UnsubscribeModal/index.tsx
src/components/settings/ContactsModal/index.tsx
src/components/utils/NotificationPwaModal/index.tsx
src/components/utils/PwaModal/index.tsx
src/pages/Login/SignatureModal/index.tsx

We currently lack a loading state for the save button in our dApp preferences. This proposed change aims to enhance user feedback by incorporating this feature. Additionally, our modals require improved handling of outside clicks. Rather than using `toggleModal`, it would be better to call `closeModal`. This change will address the issue of multiple clicks on the overlay, enhancing overall functionality.
https://github.com/WalletConnect/web3inbox/assets/19428358/d6b651f0-9ad3-4c6c-8d50-a5b75d676479
Fixes: https://github.com/WalletConnect/web3inbox/issues/282

refactor: dapp preferences modal loading state & modals outside click handlers

---

src/components/notifications/AppSelector/index.tsx

The subscribed title on the app selector panel should be invisible if there is no subscription.
Closes https://github.com/WalletConnect/web3inbox/issues/281

chore: update subscribed title logic

---

src/utils/hooks/useNotifyProjects.ts

- Change sort order from descending to ascending [Slack thread](https://walletconnect.slack.com/archives/C044SKFKELR/p1704366670043889) Resolves #321 
- Fix bug in filtering. Resolves #334 
- Resolves #334 
- Resolves #321

fix: filtering and sorting in useNotifyProjects

---

src/utils/hooks/useNotifyProjects.ts
src/utils/projects.ts

Fixes a logic error on the `useNotifyProjects` hook when have a dev mode enabled
Closes https://github.com/WalletConnect/web3inbox/issues/341

fix: projects duplicate when have a dev mode

---

src/components/notifications/AppExplorer/AppCard/AppCard.scss

The current styling solution for the app cards causing some performance issues. The `filter` or `backdrop filter` is one of the most expensive stylings and when we put more value on the `blur` filter. It'll dramatically drop the performance. We can see the effect of this in the Discover page on Safari. While we scroll, the apps are rendered to the screen with a lag.
This PR includes a refactor to optimize the background image styles of the App card. 
Closes https://github.com/WalletConnect/web3inbox/issues/355

refactor: update app card styles

---

src/components/notifications/AppSelector/AppSelector.scss
src/components/notifications/AppSelector/index.tsx
src/contexts/W3iContext/context.ts
src/contexts/W3iContext/hooks/notifyHooks.ts
src/contexts/W3iContext/index.tsx

- changed the `setTimeout` to `setInterval` in the initial loading for `notifyHooks` state
- Show loading indicator while the interval is running
Resolves #326

fix: use interval to load state incrementally

---

src/components/notifications/AppSelector/AppSelector.scss
src/components/notifications/AppSelector/LinkItemSkeleton/LinkItemSkeleton.scss
src/components/notifications/AppSelector/index.tsx
src/components/notifications/NotificationsLayout/index.tsx

We are forcing users to discover the page when they don't have any subscriptions. This causes a broken experience on the PWA. The notification list check should be on the first load since the list is loaded gradually (not at once). We shouldn't force redirecting to discover every time they open the subscriptions page. 
Closes https://github.com/WalletConnect/web3inbox/issues/333
https://github.com/WalletConnect/web3inbox/assets/19428358/74bd18d4-4dce-42c4-ac51-0158016f03ee

refactor: subscriptions mobile page and skeleton rendering logics

---

package.json
yarn.lock

- Bump notify 0.16.3  to fix the issue with being unable to unregister due to unsynced state (namely `watchSUbscriptions`, `registrationData` and `identityKeys`)
Resolves #357

chore: bump notify 0.16.3

---

src/components/notifications/AppExplorer/AppCard/AppCard.scss
src/components/notifications/AppExplorer/AppCard/SubscribeButton.tsx
src/components/notifications/AppExplorer/AppCard/index.tsx
src/components/notifications/AppExplorer/index.tsx

Adding control logic to app cards in the discovery page to show the loading state before we have the subscription data. This will fix the logic that we're showing the "Subscribe" button even though we subscribed but since we haven't loaded all subscriptions yet, it's misleading us and results bad UX.
Closes https://github.com/WalletConnect/web3inbox/issues/329
https://github.com/WalletConnect/web3inbox/assets/19428358/e25b504b-2f49-49de-a30d-75b1bd19f10e

refactor: dapps subs loading state

---

src/components/notifications/AppExplorer/AppCard/index.tsx
src/contexts/W3iContext/hooks/notifyHooks.ts
src/pages/widget/Subscribe/index.tsx
src/utils/hooks/useNotifyProjects.ts
src/utils/projects.ts

- Context: https://walletconnect.slack.com/archives/C044SKFKELR/p1704993119733469?thread_ts=1704976288.139559&cid=C044SKFKELR
- We were catching some errors and showing user friendly toasts without processing the underlying error in an observable way.
- Ensure every `catch + showErrorMessageToast` is paired to a `console.error` call
- Any other changes are ESLint/Prettier auto-fixes

fix: ensure every error toast logs the underlying error to console

---

.github/workflows/playwright.yml
.gitignore
README.md
package.json
playwright.config.ts
tests/home.spec.ts
tsconfig.json
yarn.lock

Adds Playwright testing. Initially created with `npm init playwright@latest` and then tweaks for yarn, automatic running of the dev server, and added a basic initial test.

chore: initial Playwright tests

---

src/App.scss
src/components/layout/MobileFooter/MobileFooter.scss
src/components/layout/MobileHeader/MobileHeader.scss
src/components/notifications/AppExplorer/AppExplorer.scss
src/components/notifications/AppExplorer/index.tsx
src/components/notifications/AppNotifications/AppNotifications.scss
src/components/notifications/AppNotifications/index.tsx
src/components/notifications/AppSelector/AppSelector.scss
src/index.css
src/pages/Login/Login.scss

Refactor layout styles to fix overflow issues in different situations like; subscription list, notifications (topic) page on mobile, etc.
Closes https://github.com/WalletConnect/web3inbox/issues/379
[See preview for better showcase]

refactor: update all layout styles

---

src/components/notifications/AppExplorer/AppCard/index.tsx
src/w3iProxy/notifyProviders/internalNotifyProvider.ts

Since we're calling the `handleSubmit` at once and the `subscribed` and `subscribing` values changing over time. We should watch these values in `useEffect` to handle subscribed state and take action (like show a toast message).
Closes https://github.com/WalletConnect/web3inbox-planning/issues/51
https://github.com/WalletConnect/web3inbox/assets/19428358/71063d75-68bb-4c99-adf7-909c5b8e71ab

refactor: move the subscription complete handler on useEffect

---

src/firebase-messaging-sw.ts
src/main-sw.ts

We were missing a notification handler to take certain actions on click to notification on the desktop. Refactored the Firebase service worker to pass `url` to the `data` prop of the event handler's body. 
Unlike the mobile devices, the notification handler doesn't have `url` handler as you can see the documentation below. We should pass the url to `data` object and handle the data fields inside the `notificationonclick` event handler and take action. Here, we're doing a basic thing which is opening the URL in the browser.
- MDN Docs - [ServiceWorkerRegistiration](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification)
Closes https://github.com/WalletConnect/web3inbox/issues/353

chore: add event handlers on sw to handle notifs

---

package.json
src/utils/sentry.ts
yarn.lock

- Follow-up to #382 
- Context: Sentry will _not_ capture explicit `console.error` calls by default unless specifically configured to do so.
- Adds `CaptureConsole` integration with only `error` log level being captured. Context: https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/integrations/captureconsole/
- Additionally: updates `@sentry/react` to latest
- Tested that Sentry still triggers as expected on the preview
- Rewiring all the `catch` statements touched in #382 to `throw`. This is risky 1 day before launch bc it will bail on the remaining function and may cause unwanted/unexpected changes to the app's behaviour if not done carefully.
- Adding `Sentry.captureException` alongside the added `console.error()` calls. This will create unnecessary clutter and will …

chore(config): ensure Sentry captures `console.error` calls

---

src/components/utils/PwaModal/PwaModal.scss
src/components/utils/PwaModal/index.tsx
src/pages/Login/Login.scss
src/pages/Login/index.tsx

Add web3inbox.com redirections to login and PWA modals for users to learn more incase they are directly opened to the app.web3inbox.com.
Closes https://github.com/WalletConnect/web3inbox/issues/331

refactor: website link escape hatch

---

src/components/notifications/NotificationsLayout/UnsubscribeModal/index.tsx
src/utils/toasts.ts

Refactor toast messages and toast styles for subbscribe and unsubscribe styles.
- Unsubscribe toast: (default toast): "Subscribed from [DAPP]"
- Subscribe toast: (success toast): "Subscribed to [DAPP]"
Closes https://github.com/WalletConnect/web3inbox/issues/396

refactor: update toast messages

---

src/Modals.tsx
src/components/utils/ChangeBrowserModal/ChangeBrowserModal.scss
src/components/utils/ChangeBrowserModal/index.tsx
src/components/utils/PwaModal/index.tsx
src/utils/pwa.ts

iOS Chromium browsers don't have `Add to Home Screen` functionality. For the iOS users, we should redirect them to Safari instead. Added change browser modal and refactored conditions for the other modals to make sure that mobile Chroimum users should redirected to Safari first.
Closes https://github.com/WalletConnect/web3inbox-planning/issues/48

feat: add change browser modal

---

src/Modals.tsx

- Bug: This `useEffect` is called in a loop for the duration of the signature modal being open
- It was also calling `closeWeb3Modal` unchecked i.e. even if w3m was already in a closed state
- This was causing our analytics endpoint to be spammed with `MODAL_CLOSE` events **which could lead to unintentional request floods from users that leave the app in this state.**
- **This patch ensures we first check `open: boolean` state for w3m before explicitly calling `closeWeb3Modal`**
- **This patch does not root cause why this useEffect goes into a loop once the signature modal opens, this is TBD.**
1. Go to app.web3inbox.com (or a preview that has w3m analytics enabled)
2. Use a fresh account or reset client state to ensure you get the secondary "Sign notify message" popup after w3m connect …

fix: ensure useEffect does not spam `closeWeb3Modal` + close event

---

src/constants/projects.ts
src/contexts/W3iContext/hooks/notifyHooks.ts
src/w3iProxy/listenerTypes.ts
src/w3iProxy/notifyProviders/internalNotifyProvider.ts

- issue registration in case someone `subscribe`s, `update`s or `deleteSubscription`s
- issue the action they tried to perform once again after successful registration automatically
Resolves sentry issue: https://walletconnect.sentry.io/issues/4870845805/events/572bb5d5048d40e6ad069ef2df647a9a/?project=4505754150043648
Tested via manually issueing unregister using the following addition in `internalNotifyProvider`
```
// @ts-ignore
window.forceUnregister = (account:string) => {
this.unregister({account})
}
-
```

feat: reregister if no registration while subscribing

---

src/components/general/Banner/Banner.scss
src/components/general/Banner/index.tsx
src/components/general/Icon/CrossIcon.tsx
src/components/general/LaunchBanner/LaunchBanner.scss
src/components/general/LaunchBanner/index.tsx
src/constants/localStorage.ts
src/main.tsx

Adding launch banner for announcing airdrop
Closes https://github.com/WalletConnect/web3inbox-planning/issues/28

refactor: add banner to w3i app

---

src/App.scss
src/components/general/Modal/Modal.scss
src/components/layout/Sidebar/Sidebar.scss
src/components/layout/Sidebar/index.tsx
src/index.css
src/pages/Login/Login.scss
src/pages/ScanQrCode/ScanQrCode.scss
src/pages/widget/Connect/Connect.scss
src/pages/widget/Subscribe/Subscribe.scss

Refactor layout styles that the current styling solution doesn't provide a flexibility for the banner and the main layout shifted out the screen.
Fixes https://github.com/WalletConnect/web3inbox-planning/issues/56#issuecomment-1893924547

refactor: update layout styles

---

src/components/messages/ThreadWindow/index.tsx
src/components/notifications/AppExplorer/AppCard/index.tsx
src/components/notifications/NotificationsLayout/PreferencesModal/index.tsx
src/components/notifications/NotificationsLayout/UnsubscribeModal/index.tsx
src/contexts/W3iContext/hooks/notifyHooks.ts
src/contexts/W3iContext/hooks/w3iProxyHooks.ts
src/pages/Login/SignatureModal/index.tsx
src/pages/ScanQrCode/index.tsx
src/pages/widget/Subscribe/index.tsx
src/utils/error.ts
src/utils/hooks/useNotifyProjects.ts
src/utils/notifications.ts
src/utils/projects.ts
src/w3iProxy/notifyProviders/internalNotifyProvider.ts
src/w3iProxy/w3iChatFacade.ts
tsconfig.json

- add `logError` utility
- convert all `console.error` calls to `logError` (bar `firebase-messager` as we can't use sentry there)

chore: forward errors to sentry

---

package.json
src/utils/sentry.ts
yarn.lock

- Remove console capture in favor of `logError`

chore: remove console capture

---

src/utils/sentry.ts

- Adjusts Sentry sample rate as discussed here: https://walletconnect.slack.com/archives/C044SKFKELR/p1705569596239429

chore(config): adjust Sentry sample rate to more conservative level

---

package.json
yarn.lock

- Update wagmi, thus updating `@walletconnect/ethereum-provider` to a version that has a core that uses IndexedDB.

chore: bump wagmi and w3m

---

src/components/notifications/AppNotifications/AppNotificationItemSkeleton.tsx
src/components/notifications/AppNotifications/AppNotifications.scss
src/components/notifications/AppNotifications/index.tsx
src/reducers/notifications.ts
src/utils/hooks/useNotificationsInfiniteScroll.tsx

In the subscription details page, we should show skeleton for the loading state of the notifications, this will provide better UX to the users.
Fixes https://github.com/WalletConnect/web3inbox/issues/432

feat: add skeleton for notifications loading

---

src/components/general/Icon/ArrowRightTopIcon.tsx
src/components/notifications/AppExplorer/AppCard/index.tsx
src/components/notifications/AppNotifications/AppNotifications.scss
src/components/notifications/AppNotifications/AppNotificationsHeader/AppNotificationsHeader.scss
src/components/notifications/AppNotifications/AppNotificationsHeader/index.tsx
src/utils/url.ts

On the topic details page header, make the URL clickable.
[Slack thread](https://walletconnect.slack.com/archives/C044SKFKELR/p1705685614022099)

redirect to domain on click

---

tests/shared/pages/InboxPage.ts
tests/subscribe.spec.ts

Avoid subscribing to random apps by their position on the discover page. Instead, we should only subscribe to internal ones (i.e. Notify Swift Integration Tests Prod). For now subscribing to GM Dapp for the "2 subscriptions" test case, but we must find a way to avoid polluting GM Dapp metrics with ephemeral wallet addresses.

fix: avoid subscribing to non-test apps, subscribe by name not index

---

playwright.config.ts
src/components/notifications/AppNotifications/AppNotificationItem.tsx
src/components/notifications/AppNotifications/AppNotifications.scss
src/components/notifications/AppSelector/index.tsx
tests/canary.spec.ts
tests/subscribe.spec.ts

- Use clever clamping logic :tm: to only clamp text after it has gone over the line limit, and if it has always have a show more button
- Lower clamp length 
> [!NOTE]
> You can test this by for example sending yourself a message with length 142. It won't have a show more button on mobile, but it will here
- Resolves #513

chore: add clever clamping

---

src/components/settings/NotificationsSettings/index.tsx
src/components/utils/NotificationPwaModal/index.tsx
src/utils/firebase.ts
src/utils/notifications.ts

- Per the following:
-  https://github.com/firebase/firebase-js-sdk/issues/7575
- https://github.com/firebase/firebase-js-sdk/issues/7784 
- this indicates that this issue is in the firebase SDK and is more of a warning than a critical error. The workarounds mentioned are retries.
- This PR adds best practices: wrapping the remaining call that did not `requireNotifyPermissions` before fetching firebase token to require permissions
- Also adds retry logic and gives up after 3 attempts
- On the main production deployment: https://app.web3inbox.com/notifications/new-app 
- Reset the app:
- Clear site data, 
- unregister service workers, 
- reset notifications
- Refresh
- Filter logs by "Failed to"
- Observe the following:
- It wraps the functionality of `getToken` from firebase (Where the …

chore: add console log

---

tests/shared/pages/InboxPage.ts

- Retry modal if loading qr code fails

chore: add logic to retry modal

---

package.json

Fixes that the canary was being run for multiple projects
Same as Web3Modal canary: https://github.com/WalletConnect/web3modal/blob/41e1ab9c33e5506b86de950d16797aa6b3e64b6f/apps/laboratory/package.json#L17

fix: run canary once

---

Dockerfile.canary

Seems like when a test fails it hangs the ECS task and doesn't exist. Setting `CI=true` will prevent this. [Slack conversation](https://walletconnect.slack.com/archives/C058RS0MH38/p1715173506598119)

fix: failing cases hang

---

Dockerfile.canary
docker-canary.sh
playwright.config.ts

Uploads Playwright traces to S3 (like in Web3Modal canary) to enable debugging of failures and latency regressions.

chore: canary trace uploads

---

playwright.config.ts
src/Modals.tsx
src/components/notifications/AppNotifications/index.tsx
src/components/settings/NotificationsSettings/index.tsx
src/utils/firebase.ts
tests/shared/pages/InboxPage.ts
tests/shared/pages/SettingsPage.ts
tests/shared/pages/WalletPage.ts
tests/subscribe.spec.ts

- Fixes bug where new notifications are at the bottom of the list.
- Simplify logic for ordering notifications
- Add check for message ordering in e2e tests
- run prettier

chore: reverse order for new notification

---

.github/workflows/publish_canary.yml

We are moving canaries into a different AWS account.
@devceline can you please add the following secrets to this repo
https://start.1password.com/open/i?a=BMHDRH3RNBEU3EH5L3SMXGKJTA&v=t4ntljt7ggo2tdyspp44reqlbm&i=rh5e5gtanozfc2jj7elo5tyz7y&h=team-reown.1password.com
`AWS_ECR_PUBLISHER_ACCESS_KEY_ID: $username`
`AWS_ECR_PUBLISHER_SECRET_ACCESS_KEY: $password`
The old one can be removed if it's not being used for anything else (doesn't seem like it)

feat: change canary ECR repo
