- package.json
- src/components/messages/Message/Message.scss
- src/components/messages/Message/MessageItem.tsx
- src/components/messages/Message/index.tsx
- src/components/messages/ThreadWindow/ThreadWindow.scss
- src/components/messages/ThreadWindow/index.tsx
- yarn.lock
A bounce like animation added for incoming and outgoing messages
Message sent:
https://user-images.githubusercontent.com/26746725/224707332-5670bf35-5646-4ffa-8bfe-668b20086ec4.mov
Message received:
https://user-images.githubusercontent.com/26746725/224707347-85b32531-66b5-4f2d-ae6a-057607ef10e6.mov
> Added animations for new messages sent and received

- src/components/general/Icon/CrossIcon.tsx
- src/components/messages/ThreadWindow/ThreadDropdown/ThreadDropdown.scss
- src/components/messages/ThreadWindow/ThreadDropdown/index.tsx
- src/components/messages/ThreadWindow/ThreadWindow.scss
- src/components/messages/ThreadWindow/index.tsx
- Add `ThreadDropdown` component
- Add option to leave a thread
Resolves #66
> Add dropdown to leave a chat

- src/components/messages/ThreadSelector/index.tsx
> Hide invites when searching

- package.json
- src/components/messages/ThreadWindow/index.tsx
- src/w3iProxy/chatProviders/externalChatProvider.ts
- src/w3iProxy/externalCommunicators/androidCommunicator.ts
- src/w3iProxy/externalCommunicators/communicatorType.ts
- src/w3iProxy/externalCommunicators/iosCommunicator.ts
- src/w3iProxy/externalCommunicators/jsCommunicator.ts
- src/w3iProxy/listenerTypes.ts
- src/w3iProxy/pushProviders/externalPushProvider.ts
- yarn.lock
- Fix android and ios bug with external communicators
- Bump chat client
> Upgrade chat client to 0.4.0

- .github/ISSUE_TEMPLATE/config.yml
Changed config.yml for issues. Need a manual configuration for setting up rest of features/bug report templates
N/A
> fix(issues): Changed config.yml

- src/w3iProxy/chatProviders/externalChatProvider.ts
- src/w3iProxy/externalCommunicators/androidCommunicator.ts
- src/w3iProxy/externalCommunicators/communicatorType.ts
- src/w3iProxy/externalCommunicators/iosCommunicator.ts
- src/w3iProxy/externalCommunicators/jsCommunicator.ts
- src/w3iProxy/pushProviders/externalPushProvider.ts
- Add ability to choose a provider (chat or push) when posting an external message
> Add ability to target provider

- src/components/notifications/AppExplorer/AppCard/AppCard.scss
- src/components/notifications/AppExplorer/AppCard/index.tsx
- src/components/notifications/AppExplorer/index.tsx
- src/components/notifications/AppNotifications/index.tsx
- src/contexts/W3iContext/index.tsx
- src/main.tsx
- src/utils/hooks/usePushProjects.ts
- src/utils/types.ts
- src/w3iProxy/pushProviders/internalPushProvider.ts
Query and display projects from explorer-api
Use this table template to show …
> chore(push-projects): query and display projects from explorer-api

- .env.example
- src/main.tsx
- src/w3iProxy/pushProviders/internalPushProvider.ts
- Also: fix(config): adds default VITE_EXPLORER_API_URL to env vars
> fix: internalPushProvider providerName value

- src/components/notifications/AppSelector/index.tsx
- src/components/notifications/SubscribeModal/index.tsx
- src/contexts/W3iContext/index.tsx
- src/utils/hooks.ts
- src/utils/store.ts
- Fix state setting in subscribeModal
- Remove test buttons
- Trigger subscribeModal on `push_request`
> Update subscribe modal to trigger on request

- package.json
- src/w3iProxy/chatProviders/types.ts
- yarn.lock
Bump sync client/chat client to a new version
> Update chat client

- .eslintrc.json
- src/components/notifications/AppNotifications/AppNotificationDropdown/AppNotificationDropdown.scss
- src/components/notifications/AppNotifications/AppNotificationDropdown/index.tsx
- src/components/notifications/AppSelector/index.tsx
Bring back notification dropdown button, pass actual topic 
Unblocks #107
> Bring back notification dropdown

- src/index.css
- Nicer scrollbar, doesn't work on firefox.
> Add nicer scrollbar

- src/components/account/Avatar/index.tsx
Remove extra `/` after address when writing to clipboard
Fixes #120
> Remove slash in copy

- package.json
- src/w3iProxy/listenerTypes.ts
- src/w3iProxy/pushProviders/externalPushProvider.ts
- src/w3iProxy/pushProviders/internalPushProvider.ts
- src/w3iProxy/w3iPushFacade.ts
- yarn.lock
- Updates to `push-client@0.9.0` which includes `pushWalletClient.update()` and the `push_update` event
- Integrates in `update()` and `push_update` within `internalPushProvider` & `externalPushProvider`
- Unblocks completion of #118 
> feat: integrate `pushWalletClient.update` functionality + types

- src/contexts/W3iContext/index.tsx
- Add subscription for `push_update` and `push_delete` to refresh subscriptions
> Refresh push state on delete

- package.json
- yarn.lock
> Bump chat 0.6.6

- src/utils/hooks/usePushProjects.ts
Only query dapps that configured Notify SDK.
Use this table template to show …
> fix(push-projects): only display dapps that configured push

- src/App.tsx
- src/components/account/Avatar/index.tsx
- src/components/account/Share/Share.tsx
- src/components/messages/DirectInvite/index.tsx
- src/components/messages/NewChat/index.tsx
- src/components/notifications/AppExplorer/AppCard/index.tsx
- src/components/notifications/NotificationsLayout/PreferencesModal/index.tsx
- src/components/notifications/NotificationsLayout/UnsubscribeModal/index.tsx
- src/utils/toasts.ts
- src/w3iProxy/w3iChatFacade.ts
- src/w3iProxy/w3iPushFacade.ts
* fix(facades): adds full EventEmitter forwarding - previously there was only `on`
* fix(push-events): ensure modals and toasts wait for events - `subscribe/update/unsubscribe` flows should await the appropriate `.once()` listener to fire before reacting in the UI
* refactor(ui): unify success/error toast behaviour via own util - Make toasts DRY via `showSuccess/ErrorMessageToast` utils
> fix(push-events): ensure modals and toasts wait for events, unify toast handling

- src/pages/Login/SignatureModal/index.tsx
**Critical bug fix**, sometimes `sync` would be getting the signature for identity keys, causing a state  where nothing can be synced with others. This fixes that.
> [ Critical Bug Fix ] Fix getting wrong sync signature

- package.json
- yarn.lock
- Update push-client to latest
- Number of smaller bug fixes around `subscribe` flow and client lifecycle
- Full changelog: https://github.com/WalletConnect/push-client-js/compare/0.9.0...0.9.3
> chore(deps): updates push-client to `0.9.3`

- public/fallback.svg
- src/components/notifications/AppExplorer/AppCard/AppCard.scss
- src/components/notifications/AppExplorer/AppCard/index.tsx
- src/utils/ui.ts
Fallback image on image error. Currently implemented for notification items, can be adopted for all external image assets in future
#69  (partially)
> fix: added fallback for image error

- src/contexts/W3iContext/index.tsx
- src/pages/Login/index.tsx
- Fix up issue where logging in after disconnecting causes the app to get stuck until refresh
> Fix logging and out by updating hooks

- src/contexts/W3iContext/hooks/authHooks.ts
- src/contexts/W3iContext/hooks/chatHooks.ts
- src/contexts/W3iContext/hooks/pushHooks.ts
- src/contexts/W3iContext/hooks/w3iProxyHooks.ts
- src/contexts/W3iContext/index.tsx
- src/w3iProxy/index.ts
- Add ready checks to prevent throwing errors on hook init
- Resolves issues where logging in -> subscribing -> logging out breaks app
> Add ready checks to hooks

- src/components/notifications/AppNotifications/index.tsx
- src/utils/hooks.ts
* Always show the hour/minute in notifications to help debugging
> Always show hour

- src/w3iProxy/authProviders/externalAuthProvider.ts
- src/w3iProxy/chatProviders/externalChatProvider.ts
- src/w3iProxy/externalCommunicators/communicatorType.ts
- src/w3iProxy/externalCommunicators/reactNativeCommunicator.ts
- src/w3iProxy/pushProviders/externalPushProvider.ts
Currently, there's no way to identity if a message is destined to push or chat client.
This adds `targetClient` to provide more context and forward messages to clients accordingly.
Please attach a screenshot or screen recording of features/fixes you've implemented to verify your changes. Please also note any …
> chore(target-client): specify target client when sending a message to RN

- src/contexts/W3iContext/hooks/uiHooks.ts
Hide bottom bar when one page is enabled, removing a regression
> Fix bottom bar not being hidden

- src/w3iProxy/externalCommunicators/reactNativeCommunicator.ts
Parse `messageResponse` sent by ReactNative webview.
Use this table template …
> chore(rn-communicator): parse message response

- src/w3iProxy/index.ts
- src/w3iProxy/pushProviders/externalPushProvider.ts
- `push_proposal` -> `push_request`
> Fix request not triggering

- package.json
- src/App.tsx
- src/contexts/W3iContext/context.ts
- src/contexts/W3iContext/hooks/chatHooks.ts
- src/contexts/W3iContext/hooks/pushHooks.ts
- src/contexts/W3iContext/index.tsx
- src/pages/Login/SignatureModal/index.tsx
- src/pages/Login/index.tsx
- src/w3iProxy/index.ts
- src/w3iProxy/listenerTypes.ts
- src/w3iProxy/pushProviders/externalPushProvider.ts
- src/w3iProxy/pushProviders/internalPushProvider.ts
- src/w3iProxy/pushProviders/types.ts
- src/w3iProxy/w3iPushFacade.ts
- yarn.lock
- Add support for sync in push in web3inbox
- Support sync singing for push
> Add push sync support for w3i

- src/components/notifications/AppNotifications/AppNotificationItem.tsx
- src/components/notifications/AppNotifications/index.tsx
- src/contexts/W3iContext/context.ts
- src/contexts/W3iContext/hooks/pushHooks.ts
- src/contexts/W3iContext/index.tsx
- src/w3iProxy/pushProviders/externalPushProvider.ts
- src/w3iProxy/pushProviders/internalPushProvider.ts
- Fix `deletePushMessage` not doing anything
- Fix `sync_update` not updating UI
- Fix `externalPushProvider` ignoring `sync_update`
> Fix internal push not syncing

- src/components/notifications/AppNotifications/AppNotificationsHeader/index.tsx
- src/components/notifications/AppNotifications/index.tsx
- src/components/notifications/AppSelector/index.tsx
- src/components/utils/AuthProtectedPage.tsx
- src/contexts/W3iContext/context.ts
- src/contexts/W3iContext/hooks/uiHooks.ts
- src/contexts/W3iContext/hooks/w3iProxyHooks.ts
- src/contexts/W3iContext/index.tsx
- src/pages/Login/SignatureModal/index.tsx
- src/w3iProxy/externalCommunicators/jsCommunicator.ts
- src/w3iProxy/index.ts
- src/w3iProxy/pushProviders/internalPushProvider.ts
- add `dappContext` to W3iContext
- This is essentially a URL that will filter and navigate to pages relevant to the dapp
- Add external signing
- Allow `JsCommunicator` to talk to parent in the case of widget
> Add contextual dapp direction

- package.json
- src/w3iProxy/pushProviders/types.ts
- yarn.lock
> Bump history

- src/components/notifications/AppExplorer/AppCard/index.tsx
- src/w3iProxy/pushProviders/internalPushProvider.ts
- Add loader for sub
- Don't enable sync if it's already enabled
> Add loader for explorer sub

- src/components/notifications/AppExplorer/AppCard/index.tsx
- src/components/notifications/AppNotifications/AppNotificationsEmpty/AppNotificationsEmpty.scss
- Fix styling of overlapping notifications empty
> Fix overlapping empty notifs

- src/components/notifications/AppNotifications/AppNotificationsHeader/AppNotificationsHeader.scss
- src/components/notifications/AppNotifications/AppNotificationsHeader/index.tsx
- Add dropdown to header, to allow people to unsubscribe within widget
> Add settings to header

- src/contexts/W3iContext/hooks/pushHooks.ts
- Bubble push message event message to window parent if url matches dappOrigin
> Bubble up the push message event

- src/components/notifications/AppExplorer/AppCard/AppCard.scss
- src/components/notifications/AppExplorer/AppCard/index.tsx
- src/utils/notifications.ts
- src/w3iProxy/pushProviders/internalPushProvider.ts
- Only access desktop notifications in `https` environments.
> Fix local env sub

- package.json
- yarn.lock
- Bump push client to `0.10.8`
> Bump push client

- src/w3iProxy/pushProviders/internalPushProvider.ts
- Wrap firebase logic in try/catch
- Tested on brave with & without google notification permissions
Resolves #191
> Fix issue with subscribing on envs that do not support firebase

- src/contexts/W3iContext/hooks/pushHooks.ts
- src/w3iProxy/pushProviders/externalPushProvider.ts
- src/w3iProxy/w3iPushFacade.ts
- Add account filtering to getActiveSubs
> Filter by account in getActiveSubs

- src/pages/Login/SignatureModal/index.tsx
- If signature is rejected, allow the user to try again
Closes https://github.com/WalletConnect/web3inbox-widget/issues/14
> Gracefully fail when signature rejected

- src/components/general/BackButton/index.tsx
- src/components/general/Icon/MessageIcon.tsx
- src/components/general/Icon/NotificationIcon.tsx
- src/components/general/Icon/PencilIcon.tsx
- src/components/general/Icon/SearchIcon.tsx
- src/components/general/Icon/SettingIcon.tsx
- src/components/general/Icon/SubscribeIcon.tsx
- src/components/general/Icon/WalletConnectIcon.tsx
- src/components/notifications/AppNotifications/index.tsx
- src/contexts/W3iContext/hooks/pushHooks.ts
- Use `JSX` compliant properties
- Sort notifications
- Account for sync init in `pushHooks`
- Note, current solution for this is a stopgap, we need to look into creating events for this.
> Fix low-hanging fruit

- src/contexts/W3iContext/hooks/pushHooks.ts
- Check for new subscriptions using `sync_update`
- If after a sync update we have a subscription matching `dappOrigin`, we bubble subscription settlement
- This fixes the issue where the widget doesn't know the subscription was settled through sync instead of normal subscription flow
> Bubble sub settlement

- src/pages/widget/Subscribe/index.tsx
> Add check for if subbed

- package.json
- yarn.lock
- Bump notify
- This adds indefinite history fetching
> Bump notify

- package.json
- src/components/account/Avatar/index.tsx
- src/contexts/W3iContext/hooks/authHooks.ts
- src/main.tsx
- src/pages/Login/index.tsx
- yarn.lock
- Fix issue where sometimes disconnecting does not work
- It was caused by navigating away or changing state that would trigger navigating away before disconnecting finalizes. 
- Both these instances were fixed.
- Add temporary band-aid until wagmi updates their ethereum provider
This is still in draft because while fixing this I stumbled upon a different issue where sometimes the session does not get cleaned up, leaving behind a broken session. This prevents connecting again
> Fix not disconnecting

- src/Modals.tsx
- src/contexts/W3iContext/hooks/pushHooks.ts
- Clear push registered key on init
> fix: user not being reprompted for identity key sign on secondary wallet login

- src/utils/mixpanel.ts
- src/w3iProxy/index.ts
- src/w3iProxy/pushProviders/internalPushProvider.ts
- Conditionally disable mixpanel based on env params
> Conditionally disable mixpanel

- src/utils/hooks/useNotifyProjects.ts
- src/utils/types.ts
- Cleanup fetch logic
- use `dapp_url` instead of `home_page`
> Fix using homepage

- package.json
- src/contexts/W3iContext/hooks/authHooks.ts
- src/w3iProxy/index.ts
- yarn.lock
* See: https://github.com/WalletConnect/walletconnect-monorepo/pull/3688
* Use core canary that allows for a client instantiating core to set a custom namespace/storagePrefix
Please attach a screenshot or screen recording of features/fixes you've implemented to verify your changes. Please also note any relevant …
> chore(deps): use @walletconnect/core canary with storage prefixing

- src/App.tsx
- vite.config.ts
- Remove service worker, it isn't doing anything at the moment but introducing caching bugs
> Disable service worker registry

- index.html
- vercel.json
- Add vercel redirects
- Add snippet in `index.html`
*Tested via* Checking that the page view is visible on https://plausible.io/app.web3inbox.com
> Add plausible via vercel

- README.md
- exampleExternalProviderScripts/notifyExternalProviderScript.js
- src/App.tsx
- src/Modals.tsx
- src/components/notifications/AppExplorer/AppCard/index.tsx
- src/components/notifications/AppNotifications/AppNotificationDropdown/index.tsx
- src/components/notifications/AppNotifications/AppNotificationItem.tsx
- src/components/notifications/AppNotifications/AppNotificationsCardMobile/index.tsx
- src/components/notifications/AppNotifications/index.tsx
- src/components/notifications/AppSelector/index.tsx
- src/components/notifications/NotificationsLayout/PreferencesModal/index.tsx
- src/components/notifications/NotificationsLayout/UnsubscribeModal/index.tsx
- src/contexts/W3iContext/context.ts
- src/contexts/W3iContext/hooks/notifyHooks.ts
- src/contexts/W3iContext/hooks/providerQueryHooks.ts
- src/contexts/W3iContext/hooks/w3iProxyHooks.ts
- src/contexts/W3iContext/index.tsx
- src/pages/Login/SignatureModal/index.tsx
- src/pages/Login/index.tsx
- src/pages/widget/Subscribe/index.tsx
- src/utils/hooks.ts
- src/utils/mocks.ts
- src/utils/store.ts
- src/w3iProxy/index.ts
- src/w3iProxy/listenerTypes.ts
- src/w3iProxy/notifyProviders/externalNotifyProvider.ts
- src/w3iProxy/notifyProviders/internalNotifyProvider.ts
- src/w3iProxy/notifyProviders/types.ts
- src/w3iProxy/w3iChatFacade.ts
- src/w3iProxy/w3iNotifyFacade.ts
- Rename "push" to "notify" globally in app.
Tested by verifying everything works the same in the web app.
> Rename push to notify

- src/components/notifications/AppNotifications/AppNotificationsCardMobile/index.tsx
- src/components/notifications/AppNotifications/index.tsx
- src/components/notifications/AppSelector/index.tsx
- src/components/notifications/NotificationsLayout/UnsubscribeModal/index.tsx
- Safe guard against incorrect `wc-notify-config` format
> chore: gracefully handle incorrect config.

- src/components/notifications/AppExplorer/AppCard/index.tsx
- src/components/notifications/AppExplorer/index.tsx
- Add fallback when passing to `AppCard`
> chore: add image fallback for appcard

- package.json
- src/w3iProxy/index.ts
- yarn.lock
- Update to `core@2.10.2`, which contains prod implementation of `customStoragePrefix`: https://github.com/WalletConnect/walletconnect-monorepo/pull/3688
- Drop the explicit `:` since it's no longer required to be spec'd manually.
> fix(deps): use to `core@latest`, tweak `customStoragePrefix`

- package.json
- src/Modals.tsx
- src/components/layout/Header/index.tsx
- src/components/layout/MobileHeader/index.tsx
- src/components/layout/Sidebar/index.tsx
- src/components/notifications/AppExplorer/AppCard/index.tsx
- src/components/notifications/AppExplorer/index.tsx
- src/components/notifications/AppNotifications/AppNotificationsCardMobile/index.tsx
- src/components/notifications/AppNotifications/index.tsx
- src/components/notifications/AppSelector/index.tsx
- src/components/notifications/NotificationsLayout/UnsubscribeModal/index.tsx
- src/components/notifications/NotificationsLayout/index.tsx
- src/contexts/SettingsContext/index.tsx
- src/contexts/W3iContext/hooks/authHooks.ts
- src/contexts/W3iContext/hooks/notifyHooks.ts
- src/main.tsx
- src/pages/Login/SignatureModal/index.tsx
- src/pages/Login/index.tsx
- src/pages/widget/Subscribe/index.tsx
- src/utils/address.ts
- src/w3iProxy/authProviders/externalAuthProvider.ts
- src/w3iProxy/authProviders/internalAuthProvider.ts
- src/w3iProxy/authProviders/types.ts
- src/w3iProxy/w3iAuthFacade.ts
- yarn.lock
- Add chain data to `w3iAuthFacade`
- React to chain switching in `internalAuthProvider` 
- Allow passing chain data to `externalAuthProvider`
- Update web3modal & its config
- **Preliminary list of chains, not final**
- Adapt signature modal trigger to work with chain switching
- Remove all hard coding of `eip155:1` (except for chat components, those will be fixed at a later date)
- Remove unreferenced/dead code that communicated with parent dapp (old `iframe` widget)
Resolves #248 
- Connect via WalletConnect using a mobile wallet
- Subscribe on ethereum chain to gm dapp
- Switch to polygon chain
- ensure there is no sub to gm dapp
- subscribe to gm dapp
- switch back to ethereum, ensure original gm dapp sub is there (via topic)
- switch to a different chain try again
> feat: refactor auth address prefix

- package.json
- src/components/notifications/AppNotifications/AppNotificationItem.tsx
- src/components/notifications/NotificationsLayout/PreferencesModal/index.tsx
- src/w3iProxy/notifyProviders/externalNotifyProvider.ts
- src/w3iProxy/notifyProviders/internalNotifyProvider.ts
- src/w3iProxy/notifyProviders/types.ts
- src/w3iProxy/w3iNotifyFacade.ts
- yarn.lock
- Use latest notify client: https://github.com/WalletConnect/notify-client-js/releases/tag/0.14.3
- update preferences modal to accommodate new scope format
> chore: bump notify client 0.14.1

- src/components/notifications/AppNotifications/AppNotificationsHeader/index.tsx
-  Handle image fallback in header
- Will change once https://github.com/WalletConnect/web3inbox/issues/266 is handled
> fix: handle image fallback for header

- src/components/settings/NotificationsSettings/index.tsx
> chore: rename setting

- package.json
- yarn.lock
- Bump notify client -> `0.14.5`
Resolves #245
> chore: bump notify 0.14.5

- src/utils/notifications.ts
Updates the client type to match the [specs](https://github.com/WalletConnect/walletconnect-specs/pull/147/files#diff-25490e5dda4bcd46802fca4131439d45ab85cf408683b76c7604735dfe656edcR70).
Updates the client type to match the [specs](https://github.com/WalletConnect/walletconnect-specs/pull/147/files#diff-25490e5dda4bcd46802fca4131439d45ab85cf408683b76c7604735dfe656edcR70).
While it works as-is because echo server lowercases it, we should change it to match the specs anyway.
> fix: user lowercase echo client type

- src/components/general/Text/Text.scss
- src/components/general/Text/index.tsx
- src/components/notifications/AppNotifications/AppNotificationItem.tsx
- src/components/notifications/AppNotifications/AppNotifications.scss
Updating notification item components styles and show more and show less logics
| Screen recording        |
| ------------ |
| https://github.com/WalletConnect/web3inbox/assets/19428358/5dd46344-8a37-40f4-bd7a-80732c59e884 |
> refactor: update notification styles

- src/components/notifications/AppExplorer/AppCard/index.tsx
- src/components/notifications/AppExplorer/index.tsx
Updated the App Card description to render host name whether it's verified or not
> refactor: update app card subtitle

- src/components/general/Button/Button.scss
- src/components/general/Button/index.tsx
- src/components/general/ExternalLink/index.tsx
- src/components/general/Icon/Wallet.tsx
- src/components/general/Modal/Modal.scss
- src/components/general/Modal/Modal.tsx
- src/components/general/Text/index.tsx
- src/components/notifications/AppNotifications/AppNotifications.scss
- src/components/notifications/AppNotifications/AppNotificationsHeader/AppNotificationsHeader.scss
- src/pages/Login/Login.scss
- src/pages/Login/SignatureModal/SignatureLoadingVisual.scss
- src/pages/Login/SignatureModal/SignatureLoadingVisual.tsx
- src/pages/Login/SignatureModal/SignatureModal.scss
- src/pages/Login/SignatureModal/index.tsx
- src/pages/Login/index.tsx
- src/utils/hooks.ts
Updated signature modal depending on the designs within some component, type, and styling refactors.
- https://github.com/WalletConnect/web3inbox/issues/252#issuecomment-1755536101
Use this table template to show examples of your changes:
Screen Record
https://github.com/WalletConnect/web3inbox/assets/19428358/34942da3-3b64-4599-994b-c0d5f20785f7
> refactor: update sign modal ux

- src/components/notifications/AppSelector/AppSelector.scss
- src/components/notifications/AppSelector/index.tsx
- src/components/notifications/NotificationsLayout/PreferencesModal/PreferencesModal.scss
- src/components/notifications/NotificationsLayout/PreferencesModal/index.tsx
Fixes the notification preferences overflow issue. 
https://github.com/WalletConnect/web3inbox/issues/296
> refactor: update preferences modal styles for overflow

- src/components/settings/AppearanceSettings/AppearanceSettings.scss
- src/components/settings/AppearanceSettings/index.tsx
- src/components/settings/NotificationsSettings/NotificationsSettings.scss
- src/components/settings/NotificationsSettings/index.tsx
Refactored settings page layout sizes. 
| Before       | After        |
| ------------ | ------------ |
| <img width="2080" alt="Screenshot 2023-12-04 at 19 46 23" src="https://github.com/WalletConnect/web3inbox/assets/19428358/a3b28990-96ba-4399-a756-43e2077b0913"> | <img width="2080" alt="Screenshot 2023-12-04 at 19 46 35" src="https://github.com/WalletConnect/web3inbox/assets/19428358/126acab1-efb5-4f7a-86a2-12231ec3838f"> |
https://github.com/WalletConnect/web3inbox/issues/260#issue-1941852792
> refactor: update layout stylings

- src/components/general/Icon/ArrowRightTopIcon.tsx
- src/components/notifications/AppNotifications/AppNotificationItem.tsx
- src/components/notifications/AppNotifications/AppNotifications.scss
Adding visit link functionality with new designs for the app notification cards.
> feat: add visit link functionality for app notification card

- package.json
- yarn.lock
Upgraded w3m to the latest version. In `3.5.4`, we have an important fix for the MM connection issue. This will bring better UX when connected with MM.
See release notes: https://github.com/WalletConnect/web3modal/releases/tag/3.5.4
> chore: upgrade w3m

- src/components/notifications/AppSelector/AppSelector.scss
A slight update to the image styles of the app selector item.
Slack conversation: https://walletconnect.slack.com/archives/C044SKFKELR/p1704384062573449
> fix: app selector item image styles

- vercel.json
- Part of https://github.com/WalletConnect/web3inbox-planning/issues/35
- Applies the same headers as are already being used for Cloud app in production, see: https://github.com/WalletConnect/cloud-app/blob/develop/apps/user-dashboard/next.config.js#L37
> fix(config): apply needed XSS/clickjacking headers in vercel.json

- src/reducers/notifications.ts
- src/utils/hooks/useNotificationsInfiniteScroll.tsx
Made slight changes to the notifications reducer
> refactor: notification reducer logics and variables

- src/components/notifications/AppNotifications/index.tsx
- src/components/notifications/AppSelector/index.tsx
- src/constants/projects.ts
- src/contexts/W3iContext/context.ts
- src/contexts/W3iContext/hooks/notifyHooks.ts
- src/contexts/W3iContext/index.tsx
- src/reducers/notifications.ts
- src/utils/hooks/useNotificationsInfiniteScroll.tsx
- src/w3iProxy/notifyProviders/internalNotifyProvider.ts
- src/w3iProxy/w3iNotifyFacade.ts
- Fix unregister stale identity
- Fix new notifications not showing up 
Resolves unreported issue of new notifications not showing up
> fix: add hotfix for new messages not showing up

- package.json
- src/components/notifications/AppSelector/AppSelector.scss
- src/components/notifications/AppSelector/index.tsx
- src/contexts/W3iContext/hooks/notifyHooks.ts
- src/w3iProxy/notifyProviders/externalNotifyProvider.ts
- src/w3iProxy/notifyProviders/internalNotifyProvider.ts
- src/w3iProxy/notifyProviders/types.ts
- src/w3iProxy/w3iNotifyFacade.ts
- yarn.lock
- use `isInitialSubscriptionLoadComplete` for more accurate status
> chore: update condition

- src/constants/web3Modal.ts
- src/main.tsx
Added terms and privacy policy to w3m
Closes https://github.com/WalletConnect/web3inbox-planning/issues/43
> refactor: add terms and policy urls to w3m

- src/contexts/W3iContext/hooks/notifyHooks.ts
- The interval that refreshes state was not being cleared, causing infinite updates every 100s, preventing scope updates since scopes get updated on `refreshNotifyState`
- Resolves #381
> chore: reset interval

- package.json
- yarn.lock
- Bump notify client with sbs changes
Resolves #380 
> chore: bump notify client 0.16.4

- .github/workflows/ui_test.yml
- add missing env var for explorer
> chore: add secret for explorer

- src/components/notifications/NotificationsLayout/UnsubscribeModal/index.tsx
Changes:
> You will stop receiving all notifications from My Dapp on the Web3Inbox and connected wallets.
To:
> You will stop receiving all notifications from My Dapp on Web3Inbox and connected wallets.
> fix: grammer

- src/App.tsx
- src/components/dev/DevTimeStamp/DevTimeStamp.scss
- src/components/dev/DevTimeStamp/index.tsx
- src/main.tsx
- Add dev time stamp component
- Component shows posix timestamp 
- Timestamp is refreshed every millisecond
> chore: add dev time stamp component

- tests/subscribe.spec.ts
This was an oversight when originally shipping the tests.
Use this table …
> fix(ui-test): tests not running

- package.json
- src/Modals.tsx
- src/components/account/Avatar/index.tsx
- src/components/messages/NewChat/index.tsx
- src/index.css
- src/main.tsx
- src/pages/Login/SignatureModal/index.tsx
- src/utils/ens.ts
- src/utils/wagmiConfig.ts
- src/w3iProxy/authProviders/internalAuthProvider.ts
- src/w3iProxy/chatProviders/internalChatProvider.ts
- src/w3iProxy/index.ts
- yarn.lock
Add the email feature of the Web3Modal with the v4 alpha version. This requires a Wagmi v2 upgrade. This PR includes the required changes of the wagmi/view functions/hooks/methods.
Closes https://github.com/WalletConnect/web3inbox/issues/436
Closes https://github.com/WalletConnect/web3inbox/issues/437
[Slack conversation](https://walletconnect.slack.com/archives/C044SKFKELR/p1707527886425219)
> feat: initialize w3m email alpha

- src/utils/wagmiConfig.ts
Please include a brief summary of the change.
Use this table template to show …
> fix: metadata URL

- tests/canary.spec.ts
When the canary fails it doesn't upload the results.
> fix: failing canary results not uploaded

- Dockerfile.canary
> chore: UI canary 10 minute timeout
